name: Artistic Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: sourav052
          outputs: |
            dist/github-contribution-grid-snake-art.svg?palette=github-dark&color_snake=%2339ff14&color_snake_border=%23fff&color_dots=%23b993d6,%238ca6db,%23b993d6,%238ca6db,%2339ff14&animation_duration=2s&animation_type=wobble
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
